import {
  Sprout,
  PencilRuler,
  Cog,
  Bot,
  Compass,
  GraduationCap,
  Sigma,
  Code2,
  Wrench,
  CircuitBoard,
  Activity,
  ScanEye,
  Route,
  Brain,
  Users,
  FlaskConical,
} from "lucide-react";
export const stageIcons = [
  Sprout,
  PencilRuler,
  Cog,
  Bot,
  Compass,
  GraduationCap,
];
export const subjectIcons = {
  "mathematics-physics": Sigma,
  programming: Code2,
  "mechanical-design": Wrench,
  "electronics-sensing": CircuitBoard,
  "motion-control": Activity,
  "perception-estimation": ScanEye,
  "planning-navigation": Route,
  "robot-learning": Brain,
  "human-systems": Users,
  "robot-platforms": Bot,
  "research-practice": FlaskConical,
};
